---
- name: Apache Web Server Deployment
  hosts: all
  become: yes
  tasks:
    - name: 1. Apache (httpd) Install karein
      yum:
        name: httpd
        state: present

    - name: 2. Apache Service ko Start aur Enable karein
      service:
        name: httpd
        state: started
        enabled: yes

    - name: 3. Custom Web Page deploy karein
      copy:
        content: "<h1>Ansible Magic! Deployed on {{ ansible_hostname }} ({{ ansible_default_ipv4.address }})</h1>"
        dest: /var/www/html/index.html
